Update server.py
I have proposed a change in line 217 based on the following:
 File "server.py", line 217
    print 'HTTP server started on port 8080'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('HTTP server started on port 8080')?